
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: fballfans-auth
  redis:
    cluster:
      nodes: DDBtest008:6379, DDBtest008:6380, DDBtest008:6381, DDBtest008:6382, DDBtest008:6383, DDBtest008:6384
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    #HikariCP连接池设置，同样的条件下，页面查询响应速度提高20%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 5


  activiti:
    database-schema: ACT
    history-level: full
    database-schema-update: true
    db-history-used: true
    # 自动建表
#

#    为true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表，
#历史表没有建立，则流程图及运行节点无法展示（暂未找到可行方式）
