server:
  port: 8761
spring:
  #  profiles:
  #公司配置
  #    active: com
  #    家用配置
  #    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-server
  security:
    user:
      name: zplan
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
  #    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/