spring:
  profiles:
#公司配置
#    active: com
#    家用配置
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout: PT0S
auth:
  permits: /hello,/auth/needlogin,/auth/piccaptcha,/auth/token,/favicon.ico,/error,/emmit
