server:
  port: 8999
spring:
  application:
    name: fballfans-auth
  redis:
    cluster:
      nodes: DDBtest008:6379, DDBtest008:6380, DDBtest008:6381, DDBtest008:6382, DDBtest008:6383, DDBtest008:6384
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 1000
    max-idle: 100
    #HikariCP连接池设置，同样的条件下，页面查询响应速度提高20%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# mybatis配置
mybatis:
  type-aliases-package: com.john.domain.entity
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 10000
    #下划线匹配驼峰
    map-underscore-to-camel-case: true

management:
  security:
    enabled: false
name: ccc

# jwt 配置
jwt:
  audience:
    iss: DDB
    aud: GATEWAY
    base64-secret: ZDY1MTA3OTYxMjRmNGRhOTgzMTA3M2M0NTVmMjY3NTE=
#    expiration-seconds: 86400
#    暂时改为10天
    expiration-seconds: 864000


