server:
  port: 8779
spring:
  application:
    name: fballfans-server
  jpa:
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Shanghai
  redis:
    host: 192.168.0.101
    password: warehouse

#  rabbitmq:
#    username: johnawll
#    password: 123456
#    virtual-host: johnawll

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useUnicode=yes&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhangJW.428
    driver-class-name: com.mysql.jdbc.Driver
    #HikariCP连接池设置，同样的条件下，页面查询响应速度提高20%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 10000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 30000
  security:
    user:
      name: zplan
      password: 123456
  flyway:
    baseline-on-migrate: true

# mybatis配置
mybatis:
  type-aliases-package: com.john.auth.domain.entity
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 10000
    #下划线匹配驼峰
    map-underscore-to-camel-case: true
name: ggg
imooc:
  security:
    browser:
      loginPage: /security/needlogin


management:
  endpoints:
    web:
      exposure:
#        // SpringBootActuator监控暴露所有接口
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
    #    SpringBootAdmin本身作为一个Eureka客户端被发现，这里由于SpringBootAdmin需要进行登录，因此，此处配置SpringBootAdmin登录时使用的用户名
    metadata-map:
      user:
        name: zplan
        password: 123456
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/

logging:
  path: logs/log
  config: classpath:log4j2.xml

xxl:
  job:
    admin:
      addresses: http://192.168.0.101:8080/xxl-job-admin
    accessToken:
    executor:
      appname: ${spring.application.name}
      address:
      ip:
      port: 9991
      logpath: data/applogs/xxl-job/jobhandler
      logretentiondays: 30
#  ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#  xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
#
#  ### xxl-job, access token
#  xxl.job.accessToken=
#
#  ### xxl-job executor appname
#  xxl.job.executor.appname=${spring.application.name}
#  ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
#  xxl.job.executor.address=
#  ### xxl-job executor server-info
#  xxl.job.executor.ip=
#  xxl.job.executor.port=9999
#  ### xxl-job executor log-path
#  xxl.job.executor.logpath=data/applogs/xxl-job/jobhandler
#  ### xxl-job executor log-retention-days
#  xxl.job.executor.logretentiondays=30



