spring:
  profiles:
#公司配置
    active: com
#    家用配置
#    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout: PT0S

#      spring.rabbitmq.host=127.0.0.1
#      spring.rabbitmq.virtual-host=johnawll
#      spring.rabbitmq.username=johnawll
#      spring.rabbitmq.password=123456
auth:
  permits: /hello,/auth/needlogin,/auth/piccaptcha,/auth/token,/favicon.ico,/error,/emmit,/cron,/jack


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

