server:
  port: 8999

#  #spring-boot整合单机版redis redis作为缓存
#  spring.redis.host=192.168.31.85
#  spring.redis.port=6379
#  spring.redis.password=123456
#  #默认使用db0
#  spring.redis.database: 2
#  # 连接超时时间（毫秒）
#  spring.redis.timeout: 0
#  # 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.pool.max-active: 8
#  # 连接池最大阻塞等待时间（使用负值表示没限制）
#  spring.redis.pool.max-wait: 20000
#  spring.redis.pool.max-idle: 8
#  spring.redis.pool.min-idle: 0
spring:
  application:
    name: fballfans-auth
#    cluster:
#      nodes: DDBtest008:6379, DDBtest008:6380, DDBtest008:6381, DDBtest008:6382, DDBtest008:6383, DDBtest008:6384
#      nodes: 211.159.185.172:6379

  rabbitmq:
    username: admin
    password: ligeit
    virtual-host: tbl
  datasource:
#    url: jdbc:mysql://192.168.1.108:3306/test
    url: jdbc:mysql://211.159.185.172:3306/warehouse?useUnicode=yes&characterEncode=utf-8&useSSL=false
    username: john
    password: zhangJW.428
    driver-class-name: com.mysql.jdbc.Driver
    #HikariCP连接池设置，同样的条件下，页面查询响应速度提高20%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      allow-pool-suspension: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 5
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# mybatis配置
mybatis:
  type-aliases-package: com.john.domain.entity
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 10000
    #下划线匹配驼峰
    map-underscore-to-camel-case: true

#management:
#  security:

#    enabled: false
name: ccc

# jwt 配置
jwt:
  audience:
    iss: DDB
    aud: GATEWAY
    base64-secret: ZDY1MTA3OTYxMjRmNGRhOTgzMTA3M2M0NTVmMjY3NTE=
#    expiration-seconds: 86400
#    暂时改为10天
    expiration-seconds: 864000

#auth:
#  permits: /hello,/auth/needlogin,/auth/piccaptcha,/auth/token,/favicon.ico,/error