server:
  port: 8762
spring:
  application:
    name: admin-server
  #  profiles:
  #公司配置
  #    active: com
  #    家用配置
  #    active: dev
  mail:
    host: smtp.qq.com
    username: juwazhang@qq.com
    password: zedxlbkowthibahe
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      boot:
        admin:
          notify:
            mail:
              from: juwazhang@qq.com
              to: juwazhang@qq.com
          ui:
            title: zplan
  #  SpringBootAdmin登录时的用户名密码
  security:
    user:
      name: zplan
      password: 123456
eureka:
  instance:
    prefer-ip-address: true
    #    SpringBootAdmin本身作为一个Eureka客户端被发现，这里由于SpringBootAdmin需要进行登录，因此，此处配置SpringBootAdmin登录时使用的用户名
    metadata-map:
      user:
        name: zplan
        password: 123456
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/

logging:
  path: logs/log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS